name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - "feature/*" # To match any branch starting with 'feature/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for gcloud
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build Docker image
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} \
            --build-arg KINDE_CLIENT_ID=${{ secrets.KINDE_CLIENT_ID }} \
            --build-arg KINDE_CLIENT_SECRET=${{ secrets.KINDE_CLIENT_SECRET }} \
            --build-arg KINDE_ISSUER_URL=${{ secrets.KINDE_ISSUER_URL }} \
            --build-arg KINDE_SITE_URL=${{ secrets.KINDE_SITE_URL }} \
            --build-arg KINDE_POST_LOGOUT_REDIRECT_URL=${{ secrets.KINDE_POST_LOGOUT_REDIRECT_URL }} \
            --build-arg KINDE_POST_LOGIN_REDIRECT_URL=${{ secrets.KINDE_POST_LOGIN_REDIRECT_URL }} \
            --build-arg GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} \
            --build-arg RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/inkam-labs:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/inkam-labs:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy inkam-labs \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/inkam-labs:$GITHUB_SHA \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars=DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --set-env-vars=NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} \
            --set-env-vars=KINDE_CLIENT_ID=${{ secrets.KINDE_CLIENT_ID }} \
            --set-env-vars=KINDE_CLIENT_SECRET=${{ secrets.KINDE_CLIENT_SECRET }} \
            --set-env-vars=KINDE_ISSUER_URL=${{ secrets.KINDE_ISSUER_URL }} \
            --set-env-vars=KINDE_SITE_URL=${{ secrets.KINDE_SITE_URL }} \
            --set-env-vars=KINDE_POST_LOGOUT_REDIRECT_URL=${{ secrets.KINDE_POST_LOGOUT_REDIRECT_URL }} \
            --set-env-vars=KINDE_POST_LOGIN_REDIRECT_URL=${{ secrets.KINDE_POST_LOGIN_REDIRECT_URL }} \
            --set-env-vars=GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} \
            --set-env-vars=RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
